import initScollSuave from './modulos/scroll-suave';
import tabAnimals from './modulos/tab-animals';
import scrollAnimado from './modulos/scroll-animado';
import accordionFaq from './modulos/accordion-faq';
import initModal from './modulos/modal';
import initTooltip from './modulos/tooltip';
import initDropDownMenu from './modulos/drop-down-menu';
import initMenuMobile from './modulos/menu-mobile';
import initFuncionamento from './modulos/funcionamento';
import initFetchAnimais from './modulos/fetch-animais';
import initFetchBitcoin from './modulos/fetch-bitcoin';

initScollSuave();
tabAnimals();
scrollAnimado();
accordionFaq();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
